### ISSUE TITLE
Should RepoDriller time out if a repository takes too long to visit?

### ISSUE THREAD

**Issue by ayaankazerouni** [mauricioaniche/repodriller#101]
I'm processing some 800 repositories, and RepoDriller 'stopped functioning'. It didn't freeze Eclipse or my computer, but stopped progressing at a particular commit in a given repository. I'm going run some tests soon to figure out why this happened, but a timeout might be a good idea.

**Comment by mauricioaniche** [comment]
Hi @ayaankazerouni, if you are analyzing 800 repositories, I suggest you don't run it into the Eclipse sandbox. Let us know if you can reproduce the problem.

I fear adding a timeout for a commit to be analyzed won't solve this issue. :/

**Comment by ayaankazerouni** [comment]
Ok, found the issue. Nothing RepoDriller could have helped with. Thanks!

**Comment by davisjam** [comment]
Would any logs from RepoDriller have helped, e.g. those introduced in #102 ?

**Comment by ayaankazerouni** [comment]
Sure they would.

**Comment by mauricioaniche** [comment]
What was the issue? I'm curious now :)

**Comment by ayaankazerouni** [comment]
As @davisjam mentions in #103, one of my repositories repeatedly triggered an infinite loop (8 times, in fact :unamused:) causing each concurrent clone to be help up. So the mining couldn't progress since all threads were busy dealing with my ineptitude.

The debug messages added in #103 help to make things more explicit in `DEBUG` mode.
