### ISSUE TITLE
Update to log4j2

### ISSUE THREAD

**Issue by ttben** [mauricioaniche/repodriller#106]
Since 2015 `log4j` discourage the use of version 1
[Version 2](https://logging.apache.org/log4j/2.x/) should be used instead.
Log4J proposes a [migration page](https://logging.apache.org/log4j/2.x/manual/migration.html).
The section `Converting to the Log4j 2 API` should be the cleanest and easiest one IMO.

**Comment by mauricioaniche** [comment]
You did it! Closing this issue!
