### ISSUE TITLE
The build is platform dependent, causing the whole build to fail.

### ISSUE THREAD

**Issue by ttben** [mauricioaniche/repodriller#115]
When running `mvn clean validate` the build fails: 

> Failed tests:   shouldDetailACommit(org.repodriller.scm.subversion.SubversionRepositoryTest): expected:<Alterando conte[??]do do arquivo Matric...> but was:<Alterando conte[?]do do arquivo Matric...>

I was suspecting an encoding issue, and indeed a warning is yield stating that no encoding has been specified.

Fixing this in incoming PR.

**Comment by mauricioaniche** [comment]
Done! Closing the issue.
