### ISSUE TITLE
DiffFilters selectively load diffs into Modifications, but without DiffText

### ISSUE THREAD

**Issue by ayaankazerouni** [mauricioaniche/repodriller#126]
Bug in `CollectConfiguration#diffs(DiffFilter...)` (that I introduced...)

When filtering diffs using the `collect` API, RepoDriller was loading diffs into `Modifications`, but without any text returned from `Modification#getDiff()`. Test cases passed because I only checked that that `Modification` existed, not that the diff text existed.

### Solution
`this.diff = true` in `CollectConfiguration#diff(DiffFilter...)`. This makes it pass the condition check at the beginning of `GitRepository#getDiffText`, where it was originally failing, causing empty Diff Texts.

**Comment by mauricioaniche** [comment]
Uhh, sounds an important bug that requires releasing right now. I'll work on it today. Thanks for reporting it, @ayaankazerouni

**Comment by mauricioaniche** [comment]
merged
