### ISSUE TITLE
'start' and 'finish' callbacks to visitors

### ISSUE THREAD

**Issue by mauricioaniche** [mauricioaniche/repodriller#19]
create a 'start' and a 'finish' callback to visitors.
- start will be called before any commit is passed.
- end will be called when all commits were visited.

**Comment by davisjam** [comment]
This was implemented in #58, right?

Note that initialize and finalize are both called once per-repo, not once overall.

**Comment by mauricioaniche** [comment]
Yes. Closing this issue.
