### ISSUE TITLE
notify when it is done via email

### ISSUE THREAD

**Issue by mauricioaniche** [mauricioaniche/repodriller#24]
by email?

**Comment by davisjam** [comment]
Sounds like feature creep. I vote we cancel this issue.

**Comment by mauricioaniche** [comment]
I've had many situations in which repodriller took days to execute in a project (due to a lot of parsing etc etc). To speed up the process, I was using different VM machines to run my study in all projects that I wanted (last time, around 30 machines). Thus, I needed to know when "a machine is done", so that I could extract the CSV and drop the VM. 

In practice, I always write an ugly bash script that checks whether the repodriller java process is still running. As you can imagine, I execute this script a few times a day... 

I believe it'd be way easier if repodriller notifies me when it's done, so that I do not need to do it continuously. Any suggestions on how to do such notification?

**Comment by davisjam** [comment]
What about something like this:

1. Study inherits from Observable, and emits on completion of execute.
2. We provide sample Observers that e.g. write to a "done file" or send an email.

But I also like the idea of ongoing progress reports provided by `RepositoryMining.mine`. Related or separate issues?

**Comment by mauricioaniche** [comment]
That's a good idea! I like it! We should merge both issues, indeed. I'll open a new one, and close this one.

**Comment by mauricioaniche** [comment]
Replaced by #75
