### ISSUE TITLE
Blame in RENAMED files

### ISSUE THREAD

**Issue by mauricioaniche** [mauricioaniche/repodriller#39]
Blame fails in renamed files.

Solution: receive `Modification` and check whether it was a rename. If so, use `getOldPath`.

**Comment by chripard** [comment]
@mauricioaniche hi, i think i can solve this issue, can you assign this to me?

**Comment by mauricioaniche** [comment]
@chripard yes! just submit the PR!

**Comment by mauricioaniche** [comment]
After discussing in #53, I do not believe this is a bug. The user needs to deal with it!
