### ISSUE TITLE
Multiple threads for different projects at the same time

### ISSUE THREAD

**Issue by mauricioaniche** [mauricioaniche/repodriller#40]
Currently, thread implementation only works for a single project, i.e., one project needs to be entirely finished for the second one to start. We can then parallelize projects as well.

See this commit to understand more about how difficult this can be:
https://github.com/mauricioaniche/metricminer2/commit/8d4bdd5b4078ec4d26bff07785262e9f25f60cec

**Comment by davisjam** [comment]
I think this idea would make it harder to program against RepoDriller.

At the moment, the user's CommitVisitor(s) must be thread-safe (in case of RepositoryMining.withThreads).

If we begin handling projects in parallel, a CommitVisitor must track state associated with multiple projects at once. This is not really desirable, and I think we might then want to associate CommitVisitor instances with a single repository.

I think #64 might be a better route. Turning up the parallelism on 1 repository or doing parallel work on N repositories should take roughly the same total time (and disk overhead), but I think a thread-safe CommitVisitor is more user-friendly than a multi-SCMRepository-safe CommitVisitor.

**Comment by davisjam** [comment]
Suggest we close this with #98

**Comment by mauricioaniche** [comment]
Agreed
