### ISSUE TITLE
"easy" mode in which it doesn't parse previous commits, diffs, source code

### ISSUE THREAD

**Issue by mauricioaniche** [mauricioaniche/repodriller#41]
idea is to be faster

**Comment by mauricioaniche** [comment]
give user the choice to configure which data should be loaded, e.g.
`load(diff, sourcecode, branches, parent)`

**Comment by davisjam** [comment]
Can you clarify how this differs from use of a `CommitRange`?

**Comment by mauricioaniche** [comment]
When we build the `Commit` object, we store lots of information, such as the _diff_, the _source code_, the _list of branches_, the _parent commit_ and etc. All of this has a cost, as we have to get this data from Git.

However, if I am building a study that does not care about _parent commits_ (a good example, as I suppose most of times people do not care about it), then, this information does not need to be loaded. The same for diffs or source codes. So, it'd be a simple way to avoid extracting a lot of data that is not needed for that particular study, and thus, making it faster.

**Comment by davisjam** [comment]
Definitely do-able. Reducing the metadata loaded into `ChangeSet` might be premature optimization -- again we don't have a sense of the cost of the various pieces of metadata. But if we can do without the *diff* that should offer nice performance gains -- then the `ChangeSet` is all the user really needs.

**Comment by davisjam** [comment]
@ayaankazerouni Is this related to what you're working on?

**Comment by ayaankazerouni** [comment]
It is related in the sense that I want more granular control over what I spend time computing (diffs in my case). See #104

**Comment by mauricioaniche** [comment]
This was done in 1.4.0.
