### ISSUE TITLE
notify processors when project has changed

### ISSUE THREAD

**Issue by mauricioaniche** [mauricioaniche/repodriller#6]
if you are running the study over many projects, the processors don't know whether the project has finished/changed. Create callbacks so that the processor can be aware of it.

**Comment by davisjam** [comment]
I don't understand what this is asking for. @mauricioaniche Can you clarify?

**Comment by mauricioaniche** [comment]
I think this is already addressed by commit https://github.com/mauricioaniche/repodriller/commit/c96d1d7cb19b9bf3df99d1bf079f2129dfc2fcbc. Closing this issue!
