### ISSUE TITLE
Multiple threads on the same repo

### ISSUE THREAD

**Issue by davisjam** [mauricioaniche/repodriller#64]
If the machine has plenty of disk space, you can maintain more than one copy of a repo being mined. If a thread checkout's a revision, it does so on its own copy of the repo.

**Comment by mauricioaniche** [comment]
Hi @davisjam! This is indeed an idea!

However, during my last study, I noticed a crazy behavior from Git. I was running two instances of RepoDriller separately (i.e., two different processes), both of them doing checkouts in different repositories. Git started to fail on checkouts! 

At the time, I was rushing for a conference, so I just gave up executing two processes at the same time. However, this is something to investigate before we can dive into multiple checkouts in parallel!

**Comment by davisjam** [comment]
@mauricioaniche, that does indeed sound like very strange behavior. Any chance the instances were using the same workspace and were colliding at the file system level?

**Comment by mauricioaniche** [comment]
Yes, I am definitely sure that they were analyzing the same repo! This made me wonder whether Git has some _crazy huge global state_ somewhere. I should have some time to try to reproduce it in November!

**Comment by davisjam** [comment]
I think it's unlikely that Git maintains global state on the system. I'm more suspicious of shared state in RepoDriller.

If you were using the *same* repository in two different RepoDriller instances, I wonder if both decided to use the same directory and stepped on each other.

Here is a possible path:

1. GitRemoteRepository(String url) uses GitRemoteRepository.gitSystemTempDir to pick the temporary directory.
2. GitRemoteRepository.gitSystemTempDir uses FileUtils.GetTempDirectory
3. FileUtils.getTempDirectory uses FileUtils.getTempDirectoryPath
4. Which returns `System.getProperty("java.io.tmpdir");`, presumably the same across instances?

So then two RepoDriller instances would be using the same temp directory. Cloning repositories of the same name to this directory would result in two processes both working in the same "temp dir + repo name" directory and they would step on each other.

I think using File.createTempDirectory would resolve this issue (and be more appropriate than querying java.io.tmpdir directly?).

**Comment by mauricioaniche** [comment]
I believe _GitRemoteRepository_ uses the tmpdir as basedir. Thus, a new dir is always created when it clones the remote repo. Nevertheless, I was using the traditional _GitRepository_. 

I'll do my best to reproduce it. It might also be that I was drowning on too much data and got confused. If so, better for us: we can happily implement a better multithreading system for repodriller! I'll be back to this issue in November!

**Comment by csokol** [comment]
The 50 cents of someone who's completely away of the project since 2014:

I'm not sure how big would be the speedup if we ran repodriller in multiple
threads. I guess the bottleneck is probably the disk io as there are no CPU
intensive logic usually running. I would try to setup a raid 0 partition
and measure the performance, if there's a significant improvement then it
means the bottleneck is only disk io and there's no point of running in
multiple threads. Maybe running the work in multiple machines would give
some real improvement if there's one single huge repository being mined.

**Comment by davisjam** [comment]
Hi @csokol,

Yes, if the issue were just disk I/O you're right. But I'm anticipating doing CPU-intensive work on each checkout, e.g. static analysis, running test suites, etc. If we eliminate the global shared state (on-disk repo instance) then this can scale to the number of cores.

And yes, it might be interesting to add a distributed component. But single-machine is fine for now.

**Comment by mauricioaniche** [comment]
In an old rejected paper about the tool, we saw some good performance improvements when using threads even for basic visitors. 

For now, I'm using the beautiful power of cloud computing and using one machine per project, when I need scale.

**Comment by davisjam** [comment]
Addressed in #98
