### ISSUE TITLE
Version on maven is out of date

### ISSUE THREAD

**Issue by davisjam** [mauricioaniche/repodriller#65]
Just spent awhile tracking this down.

The version on Maven (1.2.1) doesn't include Nascimento's c96d1d7cb19 which adds initialize/finalize methods to CommitVisitor.

Can you publish the latest version?

**Comment by mauricioaniche** [comment]
I sure can, @davisjam. On my ToDo list for tomorrow!

**Comment by mauricioaniche** [comment]
Just released version _1.3.0_. It should be propagated to Maven repos in a couple hours!
